# Generated by Django 3.1.4 on 2020-12-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Company',
            new_name='company',
        ),
    ]
