# Generated by Django 3.1.4 on 2020-12-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
