# Generated by Django 3.1.4 on 2020-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='age',
            field=models.IntegerField(),
        ),
    ]
